import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer";
import { Merriweather, Raleway, Roboto } from "next/font/google";
import { auth } from "./api/auth/[...nextauth]/auth";

export const metadata: Metadata = {
  title: "LeyVen",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"], weight: "400" });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={raleway.className}>
        <main className={`max-w-screen min-h-screen`}>
          <Navbar session={session} />
          {children}
          <FooterComponent />
        </main>
      </body>
    </html>
  );
}
