import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer";
import { Inter, Montserrat, Raleway, Wallpoet } from "next/font/google";
import { Toaster } from "react-hot-toast";
import ServerCartProvider from "@/context/cart";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "LeyVen",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"], weight: "400" });
const inter = Inter({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ServerCartProvider>
          <Toaster />
          <main className={`max-w-screen min-h-screen flex flex-col flex-grow`}>
            <Navbar />
            {children}
          </main>
        </ServerCartProvider>
      </body>
    </html>
  );
}
