"use client";

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import FooterComponent from "@/components/footer";
import { AnimatePresence, motion } from "framer-motion";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname();
  return (
    <html lang="en">
      <body>
        <Navbar />
        <AnimatePresence>
          <motion.div
            key={pathName}
            initial="initialState"
            animate="animateState"
            exit="exitState"
            transition={{ duration: 0.75 }}
            variants={{
              initialState: {
                opacity: 0,
              },
              animateState: {
                opacity: 1,
              },
              exitState: {},
            }}
          >
            {children}
          </motion.div>
        </AnimatePresence>
        <FooterComponent />
      </body>
    </html>
  );
}
